import type { TargetField } from "./types.ts";

export const TARGET_FIELDS: TargetField[] = [
  {
    key: "employeeNumber",
    label: "Employee number",
    type: "string",
    required: true,
    unique: true,
    description: "Stable unique identifier in the target HRIS.",
  },
  {
    key: "firstName",
    label: "First name",
    type: "string",
    required: true,
    description: "Given name, title-cased.",
  },
  {
    key: "lastName",
    label: "Last name",
    type: "string",
    required: true,
    description: "Family name, title-cased.",
  },
  {
    key: "email",
    label: "Work email",
    type: "email",
    required: true,
    unique: true,
    description: "Corporate mailbox. Personal domains are not auto-accepted.",
  },
  {
    key: "phone",
    label: "Mobile",
    type: "phone",
    required: false,
    description: "E.164-ish digits, country inferred as IN when 10-digit local.",
  },
  {
    key: "dateOfBirth",
    label: "Date of birth",
    type: "date",
    required: false,
    description: "ISO date. Ambiguous day/month pairs are never guessed.",
  },
  {
    key: "dateOfJoining",
    label: "Date of joining",
    type: "date",
    required: true,
    description: "ISO date. Must be after date of birth + 16 years when both exist.",
  },
  {
    key: "gender",
    label: "Gender",
    type: "enum",
    required: false,
    enumValues: ["male", "female", "other", "prefer_not_to_say"],
    description: "Closed enum. Unknown source tokens escalate.",
  },
  {
    key: "department",
    label: "Department",
    type: "string",
    required: true,
    description: "Business unit / function.",
  },
  {
    key: "designation",
    label: "Designation",
    type: "string",
    required: true,
    description: "Job title in the target org catalog.",
  },
  {
    key: "employmentType",
    label: "Employment type",
    type: "enum",
    required: true,
    enumValues: ["full_time", "contract", "intern", "consultant"],
    description: "Worker classification.",
  },
  {
    key: "status",
    label: "HR status",
    type: "enum",
    required: true,
    enumValues: ["active", "inactive", "on_notice", "terminated"],
    description: "Employment lifecycle state.",
  },
  {
    key: "workLocation",
    label: "Work location",
    type: "string",
    required: false,
    description: "Plant, office, or city.",
  },
  {
    key: "managerEmployeeNumber",
    label: "Manager employee no.",
    type: "string",
    required: false,
    description: "Employee number of the reporting manager.",
  },
  {
    key: "panNumber",
    label: "PAN",
    type: "string",
    required: false,
    pattern: "^[A-Z]{5}[0-9]{4}[A-Z]$",
    description: "Indian PAN. Optional; validated when present.",
  },
  {
    key: "ctcAnnual",
    label: "Annual CTC",
    type: "number",
    required: false,
    description: "Gross annual compensation, numeric, no grouping marks.",
  },
  {
    key: "currency",
    label: "Currency",
    type: "enum",
    required: false,
    enumValues: ["INR", "USD", "EUR"],
    description: "ISO currency. Defaults to INR when CTC is present and source is silent.",
  },
];

export const FIELD_BY_KEY = Object.fromEntries(TARGET_FIELDS.map((f) => [f.key, f]));

export const REQUIRED_KEYS = TARGET_FIELDS.filter((f) => f.required).map((f) => f.key);
